// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT27qC9VUFQ0Ly4jrrR2ta39gXMP61z0s',
    appId: '1:685423286716:web:828694dd33afc4acd973b9',
    messagingSenderId: '685423286716',
    projectId: 'wellio-13758',
    authDomain: 'wellio-13758.firebaseapp.com',
    storageBucket: 'wellio-13758.firebasestorage.app',
    measurementId: 'G-8YSW8NRLLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5iK8Ry_XxDcz_71pgOzX4hoUTGZM5Axg',
    appId: '1:685423286716:android:38d743ebd3da2a7dd973b9',
    messagingSenderId: '685423286716',
    projectId: 'wellio-13758',
    storageBucket: 'wellio-13758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIa_CMj-GgP2jdbPTxwUBx2j6Cuv4Ws6M',
    appId: '1:685423286716:ios:05bce12aef0704c3d973b9',
    messagingSenderId: '685423286716',
    projectId: 'wellio-13758',
    storageBucket: 'wellio-13758.firebasestorage.app',
    iosBundleId: 'com.example.wellio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIa_CMj-GgP2jdbPTxwUBx2j6Cuv4Ws6M',
    appId: '1:685423286716:ios:05bce12aef0704c3d973b9',
    messagingSenderId: '685423286716',
    projectId: 'wellio-13758',
    storageBucket: 'wellio-13758.firebasestorage.app',
    iosBundleId: 'com.example.wellio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT27qC9VUFQ0Ly4jrrR2ta39gXMP61z0s',
    appId: '1:685423286716:web:af4a3997eb2b0133d973b9',
    messagingSenderId: '685423286716',
    projectId: 'wellio-13758',
    authDomain: 'wellio-13758.firebaseapp.com',
    storageBucket: 'wellio-13758.firebasestorage.app',
    measurementId: 'G-RZ4JPZTGM8',
  );
}
